# Generated by Django 5.1.5 on 2025-02-04 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_routine.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=25)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_routine.dept')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_routine.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=30)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_routine.batch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_routine.dept')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_routine.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to='new_routine.section')),
            ],
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=40)),
                ('notice', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='new_routine.section')),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('exam_date', models.DateTimeField()),
                ('syllabus', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='new_routine.section')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='new_routine.section')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('class_duration', models.DurationField()),
                ('course_name', models.CharField(max_length=50)),
                ('course_teacher', models.CharField(max_length=30)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='new_routine.days')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='new_routine.section')),
            ],
        ),
    ]
