# Generated by Django 5.1.5 on 2025-02-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_routine', '0002_section_class_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='exam_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
