# Generated by Django 5.1.5 on 2025-02-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_routine', '0003_exams_exam_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='paused',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
