# Generated by Django 5.1.5 on 2025-02-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_routine', '0004_exams_paused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='paused',
        ),
        migrations.AddField(
            model_name='classes',
            name='paused',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
